In [6]:
import pandas as pd
import numpy as np


from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import r2_score


from sklearn import preprocessing
from sklearn.model_selection import cross_val_score


from sklearn.metrics import mean_squared_error
from sklearn.neural_network import MLPRegressor

from sklearn.model_selection import GridSearchCV

from scipy.special import logit
from sklearn.model_selection import TimeSeriesSplit
tscv = TimeSeriesSplit(n_splits = 4)




In [4]:
scaler = MinMaxScaler()

df= pd.read_csv("DFVariables_Election.csv", index_col = 0)
dftest = pd.read_csv("DFVariables_ElectionTEST.csv", index_col = 0)
display(df)
X_train = df[["Social benefits","Homeprice","Income","Bankruptcy","Laborforce"]]
y_train = df["Electionresult"]
X_train = scaler.fit_transform(X_train)
X_test =  dftest[["Social benefits","Homeprice","Income","Bankruptcy","Laborforce"]]
y_test = dftest["Electionresult"]
X_test = scaler.transform(X_test)

Regiocode  Population  Immigrants  Social benefits  Homeprice    Income  \
0       G1680    1.068825   10.282956        -1.869934  24.823141  5.813264   
1       G1959    0.695107    6.231074         0.202074  16.540965  5.210921   
2       G0358    0.403693    2.781515        -0.132528  26.465343  5.836617   
3       G0197    0.079268   -0.195520         1.157618  25.154637  5.755499   
4       G0569   -0.366356   -0.247573        -0.251652  25.901639  5.690203   
..        ...         ...         ...              ...        ...       ...   
351     G0637    0.328183    1.469634         3.966928  -1.656670  0.000000   
352     G0638    0.326062    1.876911         2.266697  -2.539691  0.256396   
353     G1730   -0.078499    2.002775         0.941794  -1.339607  0.672403   
354     G0879    0.465212    2.192951         1.874646  -2.051091  0.424127   
355     G0193    1.043475    1.800324         2.204826  -1.575706  0.602410   

     Bankruptcy  Population Density  Unemployment  Laborforce  Electionresult  
0     22.333913                92.0    -15.000000    2.235031       -0.339541  
1     22.075703               775.0      0.793651    2.584089       -0.567556  
2     19.932434              1057.0     -7.166212    1.628950       -0.522940  
3     17.593361               853.0     -2.857143    2.778095       -0.507016  
4     22.287009              1043.0     13.888889    1.987726       -0.602941  
..          ...                 ...           ...         ...             ...  
351    1.923668              3540.0     17.628205    0.426136        0.199025  
352    1.923668               384.0      6.111111   -1.051254        0.390655  
353   13.509308               225.0     25.000000    0.632716        0.185393  
354   13.301216               176.0      6.875000   -0.176624        0.503244  
355   12.553296              1091.0     12.500000   -0.302746        0.219409  

[1780 rows x 11 columns]

Length X_train: 1780
Length y_train: 1780
Length X_test: 356
Length y_test: 356
[[0.36508568 0.79154104 0.96643634 0.3624417  0.55134364]
 [0.40962339 0.71988625 0.95967766 0.36012095 0.56833568]
 [0.40243114 0.80574885 0.96669837 0.3408575  0.52183975]
 ...
 [0.42552364 0.56518917 0.90875254 0.28312719 0.47334338]
 [0.44557527 0.55903363 0.90596671 0.28125689 0.43394495]
 [0.45267247 0.56314651 0.90796716 0.27453467 0.42780533]]
0     -0.339541
1     -0.567556
2     -0.522940
3     -0.507016
4     -0.602941
         ...   
351    0.199025
352    0.390655
353    0.185393
354    0.503244
355    0.219409
Name: Electionresult, Length: 1780, dtype: float64


In [121]:
# parameters = {'solver': ['lbfgs'], 'max_iter': [1000,1100,1200,1300,1400,1500,1600,1700,1800,1900,2000 ], 'alpha': 10.0 ** -np.arange(1, 10), 'hidden_layer_sizes':np.arange(10, 15), 'random_state':[0,1,2,3,4,5,6,7,8,9]}
parameters = {"activation":["identity","logistic","tanh","relu"],
              "solver":['lbfgs'],
              'alpha': 10.0 ** -np.arange(1, 10),
              'hidden_layer_sizes':[
                  (50, 40, 30, 20), (50,30,40,20),
                  (20,30,40,20),(40,30,40,20),
                  (40,50,30,20),(10,20,30,40),
                  (40,20,30,20),(20,30,40,50)
              ]}

In [122]:
tscv = TimeSeriesSplit(n_splits = 4)


gsc = GridSearchCV(
        estimator=MLPRegressor(verbose=0),
        param_grid= parameters,
        cv=tscv, scoring='neg_root_mean_squared_error', verbose=0, n_jobs=-1)
grid_result = gsc.fit(X_train, y_train)
best_params = grid_result.best_params_
print(best_params)

/opt/conda/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/conda/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  self.n_iter_ = _check_optimize_result("lbfgs", opt_res, self.max_iter)
/opt/conda/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:500: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REAC

{'activation': 'logistic', 'alpha': 1e-08, 'hidden_layer_sizes': (50, 40, 30, 20), 'solver': 'lbfgs'}


In [120]:
regressor = MLPRegressor(activation= 'relu', alpha= 0.001, hidden_layer_sizes= (50,40,30,20), solver= 'adam')
print("Cross val r2: ")
results = cross_val_score(regressor, X_train,y_train, cv = tscv, scoring = "r2")
print(results)
print("Cross val r2 mean:")
print(results.mean())

print("\n")
results = cross_val_score(regressor, X_train,y_train, cv = tscv, scoring = "neg_root_mean_squared_error")
print("Cross val RSME: ")
print(results)

print("Cross val RSME mean: ")
print(results.mean())

Cross val r2: 
[-63.98802453 -27.26293682  -4.66408379 -17.0592457 ]
Cross val r2 mean:
-28.24357270690024


Cross val RSME: 
[-0.56082839 -0.46132668 -0.22103334 -0.66514082]
Cross val RSME mean: 
-0.47708230832259924


In [119]:
regressor = MLPRegressor(activation= 'relu', alpha= 0.001, hidden_layer_sizes= (50,40,30,20), solver= 'adam')

regressor.fit(X = X_train,y = y_train)
y_pred= regressor.predict(X_train)

print("R2 train:")
print(r2_score(y_train,y_pred))
print("RMSE train:")
print(np.sqrt(mean_squared_error(y_train,y_pred)))
y_pred = regressor.predict(X = X_test)
print("R2 test:")
print(r2_score(y_test,y_pred))
print("RMSE test:")
print(np.sqrt(mean_squared_error(y_test,y_pred)))



R2 train:
0.8751023861072383
RMSE train:
0.1209410002402766
R2 test:
-10.976480893060039
RMSE test:
0.22607736505858578
